#!/bin/bash

function finish() {
	f="${1}"

	# No control fd: bail out
	[[ -z "${f}" || -z "${SILEO}" ]] && return
	sileo=(${SILEO})

	# Sileo control fd version < 1: bail out
	[[ ${sileo[1]} -ge 1 ]] || return

	echo "finish:${f}" >&${sileo[0]}
}

finish restart
exit 0
