#!/bin/bash

#Part 2: fix giveMeRoot
chmod 4755 /Applications/Sileo.app/giveMeRoot
chown root:admin /Applications/Sileo.app/giveMeRoot

echo =========================
echo Sileo Compatibility Layer by Samg_is_a_Ninja
echo If cydia gives you source configured multiple times error, open cydias sources page to automatically fix the error.
echo Thanks for installing
echo =========================
